= Using Debian GNU/Linux for C++ Development
:icons: font
:toc:
:numbered:
:sectlinks:
// Images and figures
:figure-caption!:
:source-highlighter: prettify
//                   coderay highlightjs prettify pygments
:coderay-linenums-mode: inline

Developing {cpp} applications under GNU/Linux, allows you to use top-level http://www.fsf.org/about/what-is-free-software[freedom-respecting] {cpp} compilers (gcc, clang) and numerous high-quality freedom-respecting libraries (Boost, Qt, etc.).

Here I'll outline how to install the Debian _Testing_ distribution, which gives you fairly current versions of the compilers (as opposed to the Debian _Stable_ distribution, in which program-versions are lagging behind -- but _Stable_ is great for servers, production rolled-out systems, etc.)

== Debian GNU/Linux

Distributions (https://www.debian.org/releases/):

* *Debian Stable* (https://www.debian.org/releases/stable/) +
Should be used for server applications, production rolled-out systems, ...

* *Debian Testing* (https://www.debian.org/releases/testing/) +
This is an option for a development workstation. It's usually stable enough, and you get the newest compilers and libraries. +
(But you should know your way around the virtual console (that you get when hitting Ctrl-F1): in case the Graphical Desktop Environment gets messed up, you can then still store your work to usb, and then safely reinstall the operating system).

=== Installing Debian Testing

* Methods
** *Method a)* +
Install _Debian Testing_ from iso-image (iso image regenerated weekly)
** *Method b)* +
Install _Debian Stable_ from iso-image first; and then update to _Debian Testing_.

Method b) is safer, since the installer is guaranteed to work. But Method a) is faster. +
Below I'll outline Method b).

* Note on Architecture:
** *i386* +
is for 32-bit x86 processors or for 64-bit processors
** *amd64* +
is for 64-bit processors (common today)

==== Obtaining the ISO-image

You have options between Jigdo or Http/Ftp Download ... +
(Http/Ftp is easier)

https://www.debian.org/CD/ see below for details

Http or FTP Download::
Download Link: https://www.debian.org/CD/http-ftp/ +
(You need only a single CD; because whatever else you want can be obtained via APT [Advanced Packaging Tool], once the base system is installed). +
Download _Stable_ (later you'll see how to upgrade to _Testing_)

Jigdo::
To get the iso-image, I can recommend using a tool called jigdo (`sudo apt-get install jigdo-file`). +
It downloads individual deb-packages and then constructs the iso-image. +
Download Link: https://www.debian.org/CD/jigdo-cd/ +
All you need is +
`debian-x.y.z-arch-CD-1.jigdo` and +
`debian-x.y.z-arch-CD-1.template` +
Download _Stable_ (later you'll see how to upgrade to _Testing_) +
+
Now download the iso-image with:
+
[source,bash]
----
jigdo-lite  debian-x.y.z-arch-CD-1.jigdo
----
+
*Setting ~/.jigdo-lite* +
Once downloads have started with jigdo, you can stop with (Ctrl-C) and then start it again, which will resume. If you've download a bit already, jigdo will have created the file `~/.jigdo-lite`. Its recommended to edit this file (to *increase the `timeout`*), particularly if you're behind a corporate company proxy or firewall:
+
[source,bash]
----
jigdo=''
debianMirror='http://httpredir.debian.org/debian'
nonusMirror=''
tmpDir='.'
jigdoOpts='--cache jigdo-file-cache.db'
wgetOpts='--passive-ftp --dot-style=mega --continue --timeout=15000'
scanMenu=''
----
+
*Reusing deb-files from existing iso-images* +
If you have old iso-images already, you can mount them, and then let jigdo search them for needed deb-packages: +
often jigdo will find some unchanged packages from older Debian Releases that it can reuse.
+
* Mount old iso-image:
+
[source,bash]
----
sudo mkdir /mnt/deb_img1
sudo mount -t iso9660 -o loop old_debian_image.iso /mnt/deb_img1
----
When jigdo-lite asks for "Files to scan", give it the mounted path from above `/mnt/deb_img1`

==== Write ISO-image to USB and install new Operating System

* Write ISO-image to USB stick
+
See https://www.debian.org/CD/faq/#write-usb
+
** Insert USB stick
** If USB is automounted, then unmount first: `umount /media/Username/UsbLabel`
** Note that to determine the device (needed in the next step), hit `dmesg` after having inserted the USB-stick: +
Check if your system shows something like `/dev/sda...`, or `/dev/sdb...`, ... +
and then copy the image to the device `/dev/sda`, or `/dev/sdb`, or ... as follows:
** Copy ISO-image to USB-device:
+
[source,bash]
----
sudo cp debian-x.y.z-arch-CD-1.iso /dev/sdx    ## where /dev/sdx is /dev/sda or /dev/sdb or ...
----
** If your USB stick is stuffed up (the writing seems to take years...), then possibly do something like this first: +
(This will format the USB stick... )
+
[source,bash]
----
## this will format the USB stick - do only if necessary

sudo fdisk /dev/sdx  ## /dev/sda or /dev/sdb or ...

  p ## print the partition table

  d ## delete a partition
  d ## delete a partition
  d ## until all deleted

  p ## print the partition table (all emtpy)

  n ## add a new partition
  p ## primary
    ## <Enter>
    ## <Enter>
    ## <Enter>

  t ## change a partition type
  b ## W95 FAT32

  p ## print the partition table

  w ## write table to disk and exit


sudo mkfs.vfat -n 'MYSTICK' -I /dev/sdx1  ## /dev/sda1 or /dev/sdb1 or ...
----
+
Also make sure that the USB stick is unmounted.
* Install Debian (Stable) Operating System from USB
** Have USB stick attached and start PC (all the while hitting F12, Del -> to enter Boot Menu)
** In Boot Menu, specify booting from USB
** Exit Boot Menu
** Install Debian, but no desktop environment yet (we'll add that later)
** Boot into your new (command-line) system
** Upgrade and check networking
+
[source, bash]
----
su -
        ## enter root password
apt-get update     ## fetch newest package lists
apt-get upgrade    ## upgrade all already-installed packages, if the lists show newer versions thereof
----
+
If apt-get does not work, because of networking problems, then the reason may be that your're behind a windows company proxy or firewall. In that case see <<_fix_up_with_cntlm, the section of fixing up networking (cNTLM etc.)>>.

* Change _Debian Stable_ to _Debian Testing_
** In the freshly started OS, log on to the commandline
** Change to root user, and change `/etc/apt/sources.list` from stable to the testing distribution as follows:
+
[source,bash]
----
su -
        ## enter root password
nano /etc/apt/sources.list
----
+
&#8230; now change `/etc/apt/sources.list` to the following +
and replace every occurrence of `stretch`, with the current https://www.debian.org/releases/testing/[codename for the testing distribution] (at the time of writing it was "stretch", but it may well be "buster", ... by the time you read this).
+
[source]
----
deb     http://httpredir.debian.org/debian stretch main contrib
deb-src http://httpredir.debian.org/debian stretch main contrib

deb     http://security.debian.org/        stretch/updates main
deb-src http://security.debian.org/        stretch/updates main

deb     http://httpredir.debian.org/debian stretch-updates main
deb-src http://httpredir.debian.org/debian stretch-updates main
----
** Update apt
+
[source,bash]
----
apt-get update         ## fetch newest package lists
apt-get upgrade        ## upgrade all already-installed packages, if the lists show newer versions thereof
apt-get dist-upgrade   ## allow upgrades to packages from the new distribution
----
+
This will upgrade your system to testing!!

* Install sudo and add your user to the sudo group
+
[source,bash]
----
apt-get install sudo
adduser Username sudo
----

* Install a Graphical Desktop Environment
+
[source,bash]
----
sudo tasksel  ## repeated spacebar selects/deselects
----

=== Your monitor needs a proprietary driver?

If the graphics does not seem to work, you might have a monitor that needs a proprietry driver. +
Don't support products that come with a "secret" driver, that people can neither inspect nor change. +
But if you still really want to use it, then you might e.g. need the package `firmware-linux-nonfree` from the `non-free` section.

Hit Ctrl-Alt-F1 and log in to the virtual terminal.

Edit `/etc/apt/sources.list` to include the `non-free` section:
[source]
----
deb     http://httpredir.debian.org/debian stretch main contrib non-free
----

Then issue these commands:
[source,bash]
----
apt-get update
apt-get install firmware-linux-nonfree
----

=== Keeping your system up to date

* apt-get
+
[source,bash]
----
sudo apt-get update   &&   sudo apt-get -y upgrade   &&   sudo apt-get -y dist-upgrade   &&   sudo apt-get -y autoremove
----
+
_alternative_
+
* aptitude (`sudo apt-get install aptitude`)
+
[source,bash]
----
sudo aptitude update   &&   sudo aptitude -y upgrade   &&  sudo aptitude -y full-upgrade
----

=== Networking

Have a look at `/etc/network/interfaces` and `/etc/NetworkManager/NetworkManager.conf`. +
In particular, you might want to set `managed=true` in `/etc/NetworkManager/NetworkManager.conf` (see https://wiki.debian.org/NetworkManager#Wired_Networks_are_Unmanaged[here]).

[[_fix_up_with_cntlm]]
=== Fix up networking if you are behind a Windows Proxy (corporate company proxy, firewall, NTLM, ...)

==== Avoid `apt-get` "Hash Sum Mismatch" errors, behind windows proxies

Windows proxies can be rather messed up (in terms of their protocol implementation) and not work smoothly with APT. +
Just assume you've got a bad proxy, and get it to work by +
creating the file `/etc/apt/apt.conf.d/99fixbadproxy` with the following content:

[source]
----
Acquire::http::Pipeline-Depth 0;
Acquire::http::No-Cache true;
Acquire::BrokenProxy    true;
----

If your proxy is not broken, you can still use these settings. They should not cause problems.

==== Install cNTLM!

cNTLM is a proxy on your computer (`localhost`), to which you connect; and which enables seamless communication with the windows proxy.

[source]
----

|--------------------------------------------------|
|                     GNU/Linux                    |
|                                                  |
|  ------------------              ----------      |           -----------------
|  | normal program |              |  cntlm |------------------| Windows Proxy |
|  |  e.g. wget     |              ----------      |           -----------------
|  ------------------              host: localhost |            host:     ...
|                                  port: 3128      |            port:     ...
|                                                  |            username: ...
| http_proxy=http://localhost:3128                 |            password: ...
|--------------------------------------------------|

----

Before installing cNTLM, there are 2 possibilities:

* On some windows-networks, GNU/Linux networking will not work at all: `sudo apt-get update` will fail. In that case you must download the cNTLM deb-package from a different computer and transfer it to the target-computer with a usb stick. See <<_install_cntlm_with_usb>>.
* On other windows-networks, basic GNU/Linux networking will work +
with `/etc/apt/apt.conf` having something like
+
[source]
----
Acquire::ftp::Proxy  "http://username:pass@host:port";
Acquire::http::Proxy "http://username:pass@host:port";
----
+
In this case you can use `apt-get` to get cntlm. See <<_install_cntlm_via_apt>>.

[[_install_cntlm_with_usb]]
===== Installing cNTLM via USB (deb package)

If you network does not work (`sudo apt-get update` does not work), then you have to load the deb package for cntlm from another PC and copy it to the target-PC via USB:

https://packages.debian.org/stable/cntlm

Underneath the textinput field you can select your distribution.

At the bottom of the page you'll find a heading "Download cntlm", followed by a table listing different architectures. Click on the architecture that you need (e.g. `amd64`, or `i386`). +
On the new page... download the deb file `cntlm_x.y.z-w_amd64.deb`

Load `cntlm_x.y.z-w_amd64.deb` onto a usb stick.

Mount it on your target-PC.

[source,bash]
----
sudo mkdir           /mnt/usb

## insert usb and find it's device (/dev/sdb1, or /dev/sda1, or...) at the end of the output of the command:  dmesg
sudo mount /dev/sdx1 /mnt/usb  ## e.g. sudo mount /dev/sdb1 /mnt/usb

## install cntlm
sudo dpkg -i /mnt/usb/cntlm_x.y.z-w_amd64.deb

## unmount usb
sudo umount /mnt/usb
----

Now continue with <<_configure_cntlm_conf>>.

[[_install_cntlm_via_apt]]
===== Installing cNTLM via APT

If networking works (`sudo apt-get update` works), then you can install cNTLM from the commandline

[source,bash]
----
sudo apt-get install cntlm
----

[[_configure_cntlm_conf]]
===== Configure `/etc/cntlm.conf`

[source,bash]
----
nano /etc/cntlm.conf
----

Now restart `cntlm`:
[source,bash]
----
sudo service cntlm restart
----


cntlm is itself a proxy on the local system. To use this, we need to set the environment variables `http_proxy`, `https_proxy` and `ftp_proxy` to all be `http://localhost:3128`.
[source,bash]
----
export http_proxy=http://localhost:3128
export https_proxy=$http_proxy
export ftp_proxy=$http_proxy
----

Instead of typing this the whole time, we can create a file with those lines, which is always automatically sourced on login: +
Create `/etc/profile.d/proxy.sh`, so that environment variables  `http_proxy` and `https_proxy` are automatically set on login
[source,bash]
----
# escaping:
# note in the HEREDOC below, \\ means \ in the output!!
#                            \$ means $ in the output!!
#                            \` means ` in the output!!

sudo su -c 'cat <<EOF            > /etc/profile.d/proxy.sh
#!/usr/bin/env bash

CNTLM_HOST=localhost
CNTLM_PORT=3128
export http_proxy=http://\${CNTLM_HOST}:\${CNTLM_PORT}
export https_proxy=\$http_proxy
export ftp_proxy=\$http_proxy
EOF'
----
(view the generated file with `cat /etc/profile.d/proxy.sh`, or see link:debian_conf/with_cntlm/etc/profile.d/proxy.sh[here])

* Test:
** Logout and log back in again
+
[source,bash]
----
echo $http_proxy
     ## should show http://localhost:3128

printenv http_proxy
     ## should show http://localhost:3128

sudo printenv http_proxy
     ## will show nothing
     ## Therefore call sudo with -E:

sudo -E printenv http_proxy       ## -E : preserve existing environment variables
----

For apt to use cntlm: create `/etc/apt/apt.conf.d/95proxies` as follows
[source,bash]
----
sudo su -c 'cat <<EOF            >  /etc/apt/apt.conf.d/95proxies
# Using cntlm proxy -- see /etc/cntlm.conf
Acquire::ftp::Proxy  "http://localhost:3128";
Acquire::http::Proxy "http://localhost:3128";
EOF'
----
(view the generated file with `cat /etc/apt/apt.conf.d/95proxies`; or see link:debian_conf/with_cntlm/etc/apt/apt.conf.d/95proxies[here])

If `/etc/apt/apt.conf` exists, you can empty its contents to a single comment: +
`## see /etc/apt/apt.conf.d/95proxies`
